// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjqwjislemsryhtqpbcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqcXdqaXNsZW1zcnlodHFwYmNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNTEzNzEsImV4cCI6MjA3MzgyNzM3MX0.gUSMYIu_89-5-p4rhmTdlJdZe0u2Od65GceUEh5dboo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});